package com.indigobyte.reboothealth.error;

/**
 * API 统一错误码。
 *
 * <p>错误码面向前端和测试断言，新增业务规则时应优先复用明确错误码，避免把未知异常伪装成业务冲突。</p>
 */
public enum ErrorCode {
    PROFILE_NOT_INITIALIZED,
    PROFILE_VALIDATION_FAILED,
    HEALTH_CONSTRAINT_NOT_FOUND,
    HEALTH_CONSTRAINT_ARCHIVED,
    HEALTH_CONSTRAINT_INVALID_STATUS_TRANSITION,
    HEALTH_CONSTRAINT_INVALID_DATE_RANGE,
    GOAL_NOT_FOUND,
    GOAL_ARCHIVED,
    GOAL_INVALID_STATUS_TRANSITION,
    GOAL_INVALID_TARGET,
    IDEMPOTENCY_KEY_REQUIRED,
    IDEMPOTENCY_KEY_INVALID,
    IDEMPOTENCY_KEY_REUSED,
    PLAN_NOT_FOUND,
    PLAN_ALREADY_EXISTS,
    PLAN_CURRENT_NOT_FOUND,
    PLAN_VERSION_NOT_FOUND,
    PLAN_VERSION_NOT_DRAFT,
    PLAN_VERSION_IMMUTABLE,
    PLAN_VERSION_INVALID_PERIOD,
    PLAN_VERSION_INCOMPLETE,
    PLAN_VERSION_REVISION_CONFLICT,
    PLAN_VERSION_PERIOD_OVERLAP,
    PLAN_VERSION_SOURCE_INVALID,
    PLAN_DAY_NOT_FOUND,
    PLAN_DAY_DATE_OUT_OF_RANGE,
    PLAN_ITEM_NOT_FOUND,
    PLAN_ITEM_INVALID_VALUE,
    AGENT_RUN_NOT_FOUND,
    AGENT_RUNTIME_UNAVAILABLE,
    AGENT_RUNTIME_INVALID_OUTPUT,
    DEVICE_UNAUTHORIZED,
    DEVICE_NOT_FOUND,
    DEVICE_REVOKED,
    DEVICE_CREDENTIAL_INVALID,
    BOOTSTRAP_NOT_AVAILABLE,
    BOOTSTRAP_CODE_INVALID,
    PAIRING_SESSION_INVALID,
    ENUM_INVALID,
    VALIDATION_ERROR,
    DATA_CONFLICT,
    AUDIT_WRITE_FAILED,
    INTERNAL_ERROR
}
