package com.indigobyte.reboothealth.error;

public enum ErrorCode {
    PROFILE_NOT_INITIALIZED,
    PROFILE_VALIDATION_FAILED,
    HEALTH_CONSTRAINT_NOT_FOUND,
    HEALTH_CONSTRAINT_ARCHIVED,
    HEALTH_CONSTRAINT_INVALID_STATUS_TRANSITION,
    HEALTH_CONSTRAINT_INVALID_DATE_RANGE,
    GOAL_NOT_FOUND,
    GOAL_ARCHIVED,
    GOAL_INVALID_STATUS_TRANSITION,
    GOAL_INVALID_TARGET,
    ENUM_INVALID,
    VALIDATION_ERROR,
    DATA_CONFLICT,
    AUDIT_WRITE_FAILED
}
